// Chauffeurs
export const GET_CHAUFFEURS = "GET_CHAUFFEURS";
export const GET_CHAUFFEUR = "GET_CHAUFFEUR";
export const SET_LOADING_CHAUFFEUR = "SET_LOADING_CHAUFFEUR";
export const CHAUFFEURS_ERROR = "CHAUFFEURS_ERROR";
export const RESET_CHAUFFEURS = "RESET_CHAUFFEURS";

// Vehicles
export const GET_VEHICLES = "GET_VEHICLES";
export const GET_VEHICLE = "GET_VEHICLE";
export const SET_LOADING_VEHICLE = "SET_LOADING_VEHICLE";
export const VEHICLE_ERROR = "VEHICLE_ERROR";
export const RESET_VEHICLES = "RESET_VEHICLES";

// Business
export const GET_BUSINESS = "GET_BUSINESS";
export const GET_BUSINESS_ID = "GET_BUSINESS_ID";
export const SET_LOADING_BUSINESS = "SET_LOADING_BUSINESS";
export const BUSINESS_ERROR = "BUSINESS_ERROR";
export const RESET_BUSINESS = "RESET_BUSINESS";